### ISSUE TITLE
document hardware more consistently

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#100]
We now have some (limited) documentation on the website. I propose that we create a hardware directory to the eegsynth repo with the photo's and more details. It will be easier to maintain and extend here than on the website.

See also #74

**Comment by robertoostenveld** [comment]
@stephenwhitmarsh agreed?

**Comment by stephenwhitmarsh** [comment]
Agreed, although we could consider putting the hardware in the appropriate module, e.g. the outputCVgate and DMX module. That would remove the need to create separate documentation as well and would increase understanding of the software-hardware dependencies.

**Comment by robertoostenveld** [comment]
I have added documentation for the artnet2dmx hardware.

**Comment by robertoostenveld** [comment]
I have now also provided more documentation for artnet2neopixel hardware. I think that completes it for now.
