### ISSUE TITLE
calibration should be improved

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#121]
It should be more user-friendly, more robust and more consistent over all modules. The patching that is required for calibration should be clearly documented. 

Manual calibration involves the launchtcontrol. Automatic calibration involves some historic (sliding window) channel statistics.

@stephenwhitmarsh  started working on this in the plotcontrol module, I started working on an alternative implementation in the new smoothing and calibration modules. Part of the functionality between plotcontrol and smoothing is now replicated. 

This needs to be evaluated and disucssed.

**Comment by stephenwhitmarsh** [comment]
Skype tomorrow?

**Comment by robertoostenveld** [comment]
I just pushed the new calibration module to github.

**Comment by robertoostenveld** [comment]
for testing purposes it would help to have a generatecontrol module, just like the generatesignal. This would be very similar to an LFO, but could also include adding Gaussian and uniform noise.

**Comment by robertoostenveld** [comment]
@stephenwhitmarsh I have just committed a simple generatecontrol module. It makes sine/square/triangle/sawtooth waves, with a (launchcontrol) configurable scale, frequency, offset, noise, etc.  

![screen shot 2017-11-20 at 22 19 59](https://user-images.githubusercontent.com/899043/33042306-a5765b4e-ce41-11e7-99f4-76a55dea3265.png)

**Comment by robertoostenveld** [comment]
the launchcontrol + generatecontrol + plotcontrol module together should provide the ideal testing ground for online calibration.

**Comment by robertoostenveld** [comment]
we should consider how this fits with the post processing module, which now claims to also be doing calibration. Some replication over modules is not a problem, but we should not replicate too much.

**Comment by robertoostenveld** [comment]
calibration is now documented
