### ISSUE TITLE
The cogito audio output has a 1-second beating artefact

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#133]

**Comment by stephenwhitmarsh** [comment]
@deep-introspection lets look at this when we meet on the 7th!

**Comment by deep-introspection** [comment]
@stephenwhitmarsh Sure!

**Comment by stephenwhitmarsh** [comment]
#184 It seems the beating artefact is caused by large amplitude of the electrode-position coding. Reducing the dirac seems to solve this in the offline script.

**Comment by stephenwhitmarsh** [comment]
Seems to work now - closing
