### ISSUE TITLE
there are too many ways for calibration/scaling

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#135]
there is now postprocessing, calibrate and normalizecontrol. If we want to continue with these three functions, it should at least be clearly documented why all three are useful.

**Comment by robertoostenveld** [comment]
there is now a doc/calibration.md file as a starter

**Comment by stephenwhitmarsh** [comment]
We now have all converge on postprocessing (with added functionality in library (EEGsynth.py)), with calculations over history (mean, max, etc) done in historycontrol module
