### ISSUE TITLE
sequencer module expects categorical input

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#170]
it chooses one of several input patterns. The number of patterns is arbitrary.

One solution is to make boundaries for each pattern by something like 1/(nr_of_patterns), and select a pattern by the closest value to the 0-1 Redis value. 

This might be done by creating a function:
category = CV2Category(Redis_value,low,high)

**Comment by robertoostenveld** [comment]
the software sequencer writes a sequence of control values in Redis. These used to be scaled according to MIDI and bounded between 0 and 127.  Should those control values not simply be scaled between 0 and 1?

The values could remain integers between 0 and 127 to keep their interpretation as MIDI notes easy, and there could be an additional section

```
[output]
scale=0.00787401574803149606
offset=0 
``` 

PS note that Redis does not distinguish between integers and floats.

**Comment by stephenwhitmarsh** [comment]
Keeping MIDI values + scaling sound like a good plan.
What are your thoughts on selecting the pattern?

**Comment by robertoostenveld** [comment]
so far it was done with a knob of the launchcontrol.

e.g. launhcontrol.control021 would return 0-127, which after quantization would become 1,2,3,4
