### ISSUE TITLE
add freeze to historycontrol

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#181]
I just realized, that if we add an optional (button) control to the historycontrol module (formally normalize and smoothing), we would have implemented the 'freeze' option previously used. I.e. in the same way as the record/playback modules do. @robertoostenveld do you agree with such an approach?

**Comment by stephenwhitmarsh** [comment]
Duplicate of #145

**Comment by robertoostenveld** [comment]
agreed.

**Comment by stephenwhitmarsh** [comment]
done
