### ISSUE TITLE
recordcontrol should allow specification of channels to write

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#238]
furthermore, it should wait until all of those channels are available

**Comment by stephenwhitmarsh** [comment]
I don't see why? I can imagine plenty of scenarios in which some events
might occur later than the onset of the recording.

**Comment by robertoostenveld** [comment]
agreed, it should not wait... but it should also not give an error if the channel is not present yet. So if the channel is not available (yet), it should write zeros

**Comment by robertoostenveld** [comment]
This duplicates #62
