### ISSUE TITLE
Problem writing pre-recorded data from HDD to the buffer

### ISSUE THREAD

**Issue by mercuriaretrograda** [eegsynth/eegsynth#248]
When I tried writing pre-recorded data from HDD to the buffer I realised I don't have a playback folder inside module, as instructed in https://github.com/eegsynth/eegsynth/blob/master/doc/tutorial1.md

Hal-9000:eegsynth mariana$ cd module
Hal-9000:module mariana$ ls
accelerometer	generatesignal	outputartnet	plotsignal	rms
avmixer		heartrate	outputaudio	plotspectral	sequencer
bitalino2ft	historycontrol	outputcvgate	postprocessing	spectral
buffer		inputmidi	outputdmx512	preprocessing	synchronization
calibration	inputosc	outputgpio	quantizer	synthesizer
cogito		keyboard	outputosc	recordcontrol	volcabass
endorphines	launchcontrol	playbackcontrol	recordsignal	volcabeats
eyeblink	launchpad	playbacksignal	recordtrigger	volcakeys
generatecontrol	openbci2ft	plotcontrol	redis

**Comment by stephenwhitmarsh** [comment]
Sorry, typo: playback --> playbacksignal
Fixed it.
Cheers,
Stephen
