### ISSUE TITLE
implement an audio2ft module

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#255]
I suspect that the low-level code might already exist in FT, otherwise we might want to implement it in pure python.

This module is desired to allow something (e.g. video) to be faded in and out with the overall soundlevel. I.e. the analog audio output of the synthesizer would go into the microphone port (somehow, see *), and that would be used to construct a control signal, which in turn can be used for something else. 

*) The line level audio output signal of the synth could go into the line-in port of the Zoom microphone, which can be used (over USB) as digital audio input device. 

The same setup would also allow the ambient (e.g. audience) sound level to control something in the EEGsynth. 

The audio processing might need some specialized processing module, but in principle would be implemented the same way as EEG processing (i.e. read from FT buffer, process, write to Redis).

**Comment by robertoostenveld** [comment]
there is a C++ implementation in fieldtrip/realtime, but that one is not very clear w.r.t. the specification of the settings and devices. Hence I implemented a new one in Python, based on pyaudio. I tested it on my MacBook with the built-in microphone and with the Zoom h2n, both work fine.

**Comment by stephenwhitmarsh** [comment]
+1!
