### ISSUE TITLE
decide on the name for the "sequentializer" module

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#256]
This relates to #253

The current name is confusing, also because it resembles "sequencer", which is another module (both in hardware synths, as in the EEGsynth software ecosystem). The functionality of the "sequentializer" module does not resemble that of a sequencer in any way.

What about "edgemixer"? 

I think that "mixing" (multiple signals) relates better to what this new module does, and "edges" relate to the graphical explanation. See below for a sketch in the trivial bilinear AB case, for the (intended use) tripple bilinear ABC case. 

![2018-11-15 11 58 18](https://user-images.githubusercontent.com/899043/48548683-e011c200-e8cd-11e8-883f-c12ae32faeec.jpg)
  
It does however not convey the switching from one edge to another.

**Comment by stephenwhitmarsh** [comment]
geomixer?

**Comment by robertoostenveld** [comment]
👍🏻
