### ISSUE TITLE
rename the emg and eeg modules

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#26]
I think it is better to refer to them as the "muscle" and "brain" modules. The use of ExG is a bit confusing.

@stephenwhitmarsh, what is your opinion about this?

**Comment by stephenwhitmarsh** [comment]
I agree!

**Comment by robertoostenveld** [comment]
mac011> git commit -a
[master efe911b] renamed emg to musclue, see issue #26
 4 files changed, 3 insertions(+), 3 deletions(-)
 rename module/{emg => muscle}/README.md (100%)
 rename module/{emg/emg.ini => muscle/muscle.ini} (81%)
 rename module/{emg/emg.py => muscle/muscle.py} (98%)
 rename module/{emg/emg.sh => muscle/muscle.sh} (100%)
