### ISSUE TITLE
review whether modules have an internal state or not 

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#262]
All modules with an internal state should get a start/stop/reset button, just like the playback and the generate modules.

Right now I can only think of the sequencer module...

**Comment by stephenwhitmarsh** [comment]
Stop = Pause?
also: historycontrol

**Comment by robertoostenveld** [comment]
we should also make them more consistent

```mac011> grep -l play= module/*/*.ini
module/playbackcontrol/playbackcontrol.ini
module/playbacksignal/playbacksignal.ini
```

```mac011> grep -l enable= module/*/*.ini
module/calibration/calibration.ini
module/historycontrol/historycontrol.ini
module/historysignal/historysignal.ini
```

generateclock has the midi and redis option which act as enable/play.

sequencer does not have them (but should).

**Comment by robertoostenveld** [comment]
I think that at this moment this issue does not require further attention
