### ISSUE TITLE
the figure of plotspectral has different axes

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#274]
<img width="752" alt="screen shot 2018-11-26 at 23 32 32" src="https://user-images.githubusercontent.com/899043/49046207-a09f7b80-f1d3-11e8-9cb4-cfb4e0499f1f.png">

Both top and bottom one scale along with the location of the red and blue band, but the top one has additional text next to the blue lines which causes the freq axis to differ from the bottom one. I think it would be cleaner to have exactly the same axes in both.

**Comment by stephenwhitmarsh** [comment]
you can just change the lines of the top (and bottom) figure to fall within
the normal range :-)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by robertoostenveld** [comment]
the scaling should be linked to each other, not both free floating and slightly different
