### ISSUE TITLE
clockmultiplier/divider output name as postfix vs. prefix?

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#284]
It seems to me that this is more obvious, show up better in any list of control values/patches. This is also how the historycontrol modules works, although not how the postprocessing module works. However, the latter might be more and more split up in functional modules, allowing it also to be more consistently postfixed. 
Something to discuss together.

**Comment by robertoostenveld** [comment]
Due to lack of activity on this issue In the last 1.5 year Iwill close it. Please reopen if you consider that this needs attention
