### ISSUE TITLE
Wildcard/searchstr for midi devices

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#291]
zoals aan de tel besproken

**Comment by robertoostenveld** [comment]
I see on https://mido.readthedocs.io/en/latest/backends/rtmidi.html 

> The ALSA client and port numbers (“128:0” in this case) can change from session to session, making it hard to hard code port names or use them in config files.
>
> To get around this the RtMidi backend allows you to leave out the the port number of port number and client names. These lines will all open the port above:

This might already solve the problem on Linux...

**Comment by stephenwhitmarsh** [comment]
hmm i tried that yesterday, but that didn't work

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by robertoostenveld** [comment]
You can now use a fuzzy match to select one of the MIDI devices.
