### ISSUE TITLE
add start button to generateclock module

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#294]
as discussed over the phone. It should be possible to have the MIDI clock running without the sequencer (or whatever external device) going through its actions. The start button is needed for MIDI devices like the endorphines that do not have a physical button.

**Comment by robertoostenveld** [comment]
I propose the following logic (from the updated readme file)

The MIDI clock ticks are always send 24 times per quarter note, or 96 times per whole note. The MIDI clock signals will start ticking whenever the *play* parameter switches to true. This can be hardcoded as "1" in the ini file, but can also be mapped to a control channel in Redis. The MIDI start signal will be sent whenever the *start* parameter switches to true, or if hardcoded as "1" it will be sent when the clock starts ticking. The MIDI stop signal will be sent whenever the *start* parameter switches to false, or if hardcoded as "1"  it will be sent when the clock stops ticking. If you do not want a MIDI output signal (e.g. when no MIDI device is attached), you should hardcode the *play* parameter as "0".

**Comment by robertoostenveld** [comment]
The previous suggestion was impossible to implement cleanly, since for the state of the start button the difference between hardcoded 1/0 values and a Redis channel cannot be made. 

I think that the following would be a clean implementation:

The MIDI clock signals will start ticking whenever the *play* parameter switches to true. This can be hardcoded as "1" in the ini file, but can also be mapped to a toggle button that is represented as control channel in Redis. The MIDI start signal will be sent whenever the *start* parameter switches to true. This can be hardcoded as "1" in the ini file, but can also be mapped to a toggle button that is represented as control channel in Redis. The MIDI stop signal will be sent whenever the *start* parameter switches to false. If you do not want the MIDI start and stop signal to be sent (e.g. when your hardware device has a button), you should leave the *start* parameter empty.

I think (but have to test) that this would allow the following to be cleanly implemented:

One button to start both:
```
[midi]
play=launchcontrol.note041
start=launchcontrol.note041
```

Separate buttons:
```
[midi]
play=launchcontrol.note041
start=launchcontrol.note042
```

It always ticks, but start/stop uses a toggle button:
```
[midi]
play=1
start=launchcontrol.note042
```

It always ticks, start/stop are not sent by EEGsynth:
```
[midi]
play=1
start=
```

It starts ticking upon a toggle button, start/stop are not sent by EEGsynth:
```
[midi]
play=launchcontrol.note041
start=
```

**Comment by stephenwhitmarsh** [comment]
+1

**Comment by robertoostenveld** [comment]
this has been implemented, so the issue can be closed
