### ISSUE TITLE
Upgrade to Python 3 and Qt5

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#309]
Python 2 will retire next year, and Qt4 has already
Qt5 is much easier to build into an application apparently

https://docs.python.org/3/howto/pyporting.html

**Comment by stephenwhitmarsh** [comment]
__main__ is also slightly different in Python 2 vs 3:
https://www.guru99.com/learn-python-main-function-with-examples-understand-main.html

we can ofcourse wait until things break to upgrade to 3. not sure iwan to spend the time on all the code

**Comment by stephenwhitmarsh** [comment]
Okay, been trying to debug today:

1) configparser does NOT by default ignore inline comments with ; delimiters, since PYthon 3.3. 
Inline comments are discouraged. We have two options:
- replace all: config = configparser.ConfigParser()
with: config = configparser.ConfigParser(inline_comment_prefixes=(';',))
to revert to previous default behaviour.
- replace all inline comments by # or ; newline comments

2) Python 3 does not mix bytes and strings anymore. Not something one would have noticed perhaps, but the FieldTrip.py module breaks. I have tried to fix it, but not sure it works, as I get:
dmarequest: invalid size definitions in PUT_DAT request

But this could be due to the debugging and me not being able to flush the buffer (if that is a thing at all). In any case, the following edits do fix the complaining in which I added the encode/decode function, it might be a lead (line numbers might be one or two off):

370:      request = struct.pack('HHI', VERSION, command, sizeChunks + len(hdef)) + hdef + str.encode(extras)

509:        self.sendRaw(request + dataDef + str.encode(dataBuf))

**Comment by stephenwhitmarsh** [comment]
Okay, after restarting computer the PUT_DAT error remains. It's probably something stupid, but I need to spend more time or coffee on it, and its bedtime.

**Comment by robertoostenveld** [comment]
I have slowly been working toward this, especially with python3 on windows. The whole cogito patch works on the lenovo laptop now, which confirms that buffer communication is not a problem any more. Hence I believe that we can close this issue. I do expect that some moduled and/or some patches will reveal other python 2/3 version issues; we should solve then when we detect them.

Qt5 is another issue. If you concretely want to work on this, please open another issue.
