### ISSUE TITLE
add ini filename to Patch class

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#311]
This would make the main loop cleaner, and the Patch class more modular. It will improve sharing between (python) modules that can read/update/write the Patch instance with user-defined (gui) data, and save/load/read to ini file with its own functions.

**Comment by robertoostenveld** [comment]
the patch class could also be connecting to redis internally (on basis of the settings in the ini), i.e. you would not see any redis related code in the modules any more.

**Comment by robertoostenveld** [comment]
putting the configparser inside the patch class also makes it easy to (for now) keep on supporting the inline comments.

**Comment by stephenwhitmarsh** [comment]
thats the idea!

**Comment by robertoostenveld** [comment]
With the new modular structure this has more or less been addressed
