### ISSUE TITLE
playbacksignal cannot import configparser

### ISSUE THREAD

**Issue by Elisabeth-github** [eegsynth/eegsynth#319]
~/eegsynth/module/playbacksignal$ python playbacksignal.py -i ~/eegsynth/inifiles/playbacksigna
l.ini
Traceback (most recent call last):
  File "playbacksignal.py", line 22, in <module>
    import configparser
ImportError: No module named configparser

**Comment by robertoostenveld** [comment]
Please do

    pip install configparser

On your command line. Or the equivalent of this in anaconda
