### ISSUE TITLE
test patch should be documented or cleaned up

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#324]
There is a `test` patch at https://github.com/eegsynth/eegsynth/tree/master/patches/test which is not documented. It was added together with commit 26287b1e6f7ccc4ab86349c8b2dd4ec370d13a38, which was for the documentation. This hints at it being an inadvertent addition, just like the `rhythms` patch as detailled in #323 

I propose to clean it up, @stephenwhitmarsh agreed?

**Comment by stephenwhitmarsh** [comment]
Yes @robertoostenveld, agreed. I remember creating them, but things have changed since as well, so they are outdated at best.
