### ISSUE TITLE
implement VU meter for quick graphical feedback of control channels

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#329]
e.g. like this

<img width="512" alt="Screen Shot 2019-07-25 at 15 55 48" src="https://user-images.githubusercontent.com/899043/61880230-c9a81580-aef4-11e9-8367-0f105835be5d.png">

The bars are bouncing up and down while the control signals change.

**Comment by stephenwhitmarsh** [comment]
gorgeous!

**Comment by nicofarr** [comment]
this will be really helpful !! thanks!
