### ISSUE TITLE
Buffer shell script not compatible with WSL

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#354]
Although buffer runs when called directly, the shell script does not work for unknown (to me) reasons:

steve@DESKTOP-NN4RFID:/mnt/c/Users/Steve/eegsynth/module/buffer$ ./buffer.sh
./../../bin/parallel: line 10: $'\r': command not found
./../../bin/parallel: line 13: $'\r': command not found
./../../bin/parallel: line 16: $'\r': command not found
./../../bin/parallel: line 37: syntax error near unexpected token `elif'
'/../../bin/parallel: line 37: `elif [ $OS = Darwin ] ; then

**Comment by robertoostenveld** [comment]
The backslash r is the "return" command and dates back to typewriters. See https://en.wikipedia.org/wiki/Carriage_return

On windows, lines end in an ascii text file with \r \n as "return" and "newline", on unix only a newline is used and the return is implicit.

Git (the software) can deal with this automatically, see https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf. In your case, I suspect you used the windows git client (which will insert CRLF) and then executed the code in WSL bash.

**Comment by stephenwhitmarsh** [comment]
Sounds right! Ill pull again from WSL. Thanks :)

**Comment by robertoostenveld** [comment]
I suppose this is fixed. If not, please reopen
