### ISSUE TITLE
[launchcontrol module] Unclear how to assign sliders and pods

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#38]
When running in Python, sliding a slider will return values on screen which can be used to identify control codes. However, it remains unclear from the README or python code how to assign them to an attribute. The current ini has a [button] field, but no other fields. These would be good as example, or to describe them in the README.

I feel stupid I can't find anything else than the button-codes it in the python code. Please point me to where sliders are parsed.

**Comment by robertoostenveld** [comment]
this has been clarified over Skype
