### ISSUE TITLE
bug in buffer.sh?

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#41]
pi@raspberrypi:~/eegsynth/module/buffer $ ./buffer.sh start
./buffer.sh: 23: ./buffer.sh: OPTIONS+= : not found
./buffer.sh: 24: ./buffer.sh: OPTIONS+=1972: not found

**Comment by robertoostenveld** [comment]
probeer eerste regel eens te veranderen van

#!/bin/sh
in 
#!/bin/bash
of
#!/usr/bin/bash

Het juiste commando vind je met 
> which bash

Als dat werkt (aanpassing in script), probeer dan eens

#!/usr/bin/env bash

als het daarmee werkt, gaat het zowel op RPi en OSX

**Comment by stephenwhitmarsh** [comment]
top, dat werkt!

**Comment by robertoostenveld** [comment]
Heb je commit of pull request gedaan?

**Comment by stephenwhitmarsh** [comment]
ah nee, vergeten. morgen, moet nu uit voor een drankje. elektrodes onverrichte zaken van mijn lijf plukken. matlab op mijn pc aan het installeren want bufferviewer werkt niet lekker, en 2 gig aan scipy en MNE aan het installeren voor de heartrate

**Comment by stephenwhitmarsh** [comment]
wacht ik probeer het even

**Comment by stephenwhitmarsh** [comment]
ah moet nog een branch maken eerst. pfff.. morgen weer
