### ISSUE TITLE
improve heart rate value

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#44]
At this moments it outputs the BPM as number of beats per 10 seconds window. That means that it is quantized quite coarsely. Better is to compute the mean or median inter-beat-interval between the detected beats.

**Comment by stephenwhitmarsh** [comment]
Maximilien Chaumon @dnacombo, now at ICM, has been working shortly for our group to improve heart-beat detection: https://github.com/dnacombo/heart_functions

**Comment by robertoostenveld** [comment]
this has been stalled for about 1 year now, so better close it.
