### ISSUE TITLE
outputcvgate does not seem to output gate

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#47]
CV works, but neither through the launchcontrol or synchronizer have i been able to output gate. output i tested with microbrute and darktime, but alas i have no better way to do so.

**Comment by stephenwhitmarsh** [comment]
but even putting it into pitch - which works - the gates dont have any effect.

**Comment by robertoostenveld** [comment]
it works for me

**Comment by robertoostenveld** [comment]
please reopen if the problem persists
