### ISSUE TITLE
rewind button not working in playback module

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#57]
I noticed with @henriVDD and team "eeggames" that the rewind button was not working as expected.

**Comment by robertoostenveld** [comment]
The code looks actually fine. @henriVDD, could you try to reproduce the problem?

**Comment by HenriVDD** [comment]
@robertoostenveld , Charles has the raspberry, he will test it tonight.

**Comment by robertoostenveld** [comment]
@stephenwhitmarsh I am currently going over all record and playback options and will test this.

**Comment by robertoostenveld** [comment]
I have tested this and all works fine.
