### ISSUE TITLE
implement a new module for Novation Launchpad Mini MK2

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#63]
@stephenwhitmarsh I think this is a good one for you. You can start with the launchcontrol implementation.

**Comment by stephenwhitmarsh** [comment]
All use channel 1.

Top horizontal row, labeled 1:8 --> 104:111 **Control Change** 

Grid, goes row by row as **Notes**:
1) 0:7
2) 16:23
3) 32:39
4) 48:55
5) 64:71
6) 96:103
7) 112:119

Right vertical row, labeled A:H, extends the horizontal rows of grid, also as **Notes**: --> 
A - 8
B - 24
C - 40 
D - 56
E - 72
F - 88
G - 104
H - 120

**Comment by robertoostenveld** [comment]
@stephenwhitmarsh can you check the mapping in the readme file?

**Comment by stephenwhitmarsh** [comment]
Robert, die wou ik gaan maken!
Zal em nu checken

**Comment by robertoostenveld** [comment]
mooi, ziet er goed uit!
