### ISSUE TITLE
CH340 driver for usb2cvgate should be documented 

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#66]
@stephenwhitmarsh: as per whatsapp.

The CH340 is a (cheaper) alternative for an FTDI chip and used often in arduino clones, like the ones I used for the cvgate hardware modules. 

A driver is at least needed on OS X and it seems also on Windows. See https://www.wemos.cc/downloads or search for CH340 driver. 

We should document this and make sure that JL installs them properly.

**Comment by stephenwhitmarsh** [comment]
I will do this once I work on the serialCVgate device, and/or when I see JL.

**Comment by robertoostenveld** [comment]
this seems not to have been an issue for the last 2 years, so let's close it.
