### ISSUE TITLE
Include more 'feature' modules, specifically Hjorth

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#73]
I am interested in exploring complexity measures and came upon the Hjorth parameters. Which led me to what seems to be quite a wealth of functionality with regard to EEG features and analyses in Python:
https://github.com/forrestbao/pyeeg

**Comment by robertoostenveld** [comment]
Hjorth was part of the preprocessing module (where you could specify for each channel how it had to be re-referenced), but has been removed to reduce the clutter in the code. If it is desired, it could be added again. But the Hjorth parameters would have to be computed outside the code and stored in the ini file.

I consider it unlikely that this will be solved soon, so let me close it.
