### ISSUE TITLE
Add ft2audio in installation script

### ISSUE THREAD

**Issue by stephenwhitmarsh** [eegsynth/eegsynth#85]
Seems to have potential to become an important feature for future projects, and since we added the COGITO modules it would make it complete.

**Comment by robertoostenveld** [comment]
this is already in the eegsynth/bin/install.sh script.

**Comment by robertoostenveld** [comment]
It might be interesting to also add audio2ft, which would be useful for testing as alternative to EEG hardware and sine2ft.
