### ISSUE TITLE
gtec layout file should not be hardcoded for cogito

### ISSUE THREAD

**Issue by robertoostenveld** [eegsynth/eegsynth#87]
Rather than hardcoding the electrode numbers and hoping that they all match up, the layout file in cogito should contain all 10-20 labels (e.g. from biosemi site or fieldtrip template) and the channel labels should be string-compared to the electrodes in the layout file.

**Comment by robertoostenveld** [comment]
the cogito code should not be gtec specific, and in principle not even be 32-channel specific. It should work just as well for other EEG systems.

**Comment by stephenwhitmarsh** [comment]
With the latest commit, all gtec specific implementations should now be generic. Closed.
