### ISSUE TITLE
ENH Common Median/Mean Reference for the "Preprocessing" module

### ISSUE THREAD

**Issue by deep-introspection** [eegsynth/eegsynth#92]
How to apply a Common Median/Mean Reference? Shall we create a separate module only for this?

**Comment by robertoostenveld** [comment]
I propose 

[processing]
window=<number>
smoothing=<number>
reference=<none|average|median>

We might want to remove the montage section (which is more or less copied from the postprocessing module)

**Comment by robertoostenveld** [comment]
we also need

[processing]
lowpassfilter=xxx
highpassfilter=xxx
