### ISSUE TITLE
ENH Low/High pass filter for the "Preprocessing" module

### ISSUE THREAD

**Issue by deep-introspection** [eegsynth/eegsynth#94]
With those parameters in the .ini file:

[processing]
lowpassfilter=xxx
highpassfilter=xxx

**Comment by robertoostenveld** [comment]
@deep-introspection this has now been solved, right?

**Comment by deep-introspection** [comment]
It seems to work with the Fieldtrip sine waves generator but it would be nice to also validate this with more complex signals.

**Comment by robertoostenveld** [comment]
You could write a random noise simulator that writes data to a FT buffer, and use the spectral visualizer that @stephenwhitmarsh made ("plotsignal" module)

**Comment by deep-introspection** [comment]
It seems this is working !
